In [1]:
import tensorflow as tf

In [5]:
x = tf.constant(4,dtype=tf.int32)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
y = tf.constant([[1,2,3],[4,5,6]])
print(y)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [9]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [10]:
tf.zeros((3,4)) # zero matrix

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [11]:
tf.eye(4) # identity matrix

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [12]:
tf.random.normal((3,3),mean=0,stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.4632507 , -1.8696058 ,  0.7966001 ],
       [-0.43040773, -0.02879837, -1.2420118 ],
       [ 0.10496803, -1.11393   ,  2.0740826 ]], dtype=float32)>

In [14]:
tf.random.uniform((1,3),minval=2,maxval=3)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[2.130042 , 2.3056738, 2.8746893]], dtype=float32)>

In [19]:
z = tf.range(6,delta = 2)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 2, 4], dtype=int32)>

In [23]:
z = tf.cast(z,dtype=tf.bool)
z

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([False,  True,  True])>

In [25]:
z = tf.cast(z,dtype=tf.float32)
z

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 1., 1.], dtype=float32)>

## Mathematical Operations

In [34]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.add(x,y)
print('addition = ',z)
print()

z = tf.subtract(x,y)
print('subtraction = ',z)
print()

z = tf.divide(x,y)
print('divition = ',z)
print()

z = tf.multiply(x,y)
print('multiplication = ',z)

addition =  tf.Tensor([5 7 9], shape=(3,), dtype=int32)

subtraction =  tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)

divition =  tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)

multiplication =  tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [35]:
x+y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [38]:
z = tf.tensordot(x,y,axes=1)
# z = tf.reduce_sum(x*y,axes=0)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [40]:
a = x ** 2
b = y ** 3

print(a)
print()
print(b)

tf.Tensor([1 4 9], shape=(3,), dtype=int32)

tf.Tensor([ 64 125 216], shape=(3,), dtype=int32)


In [45]:
a = tf.random.normal((2,3))
b = tf.random.normal((3,4))

z = tf.matmul(a,b)
# z = a @ b
print(z)

tf.Tensor(
[[-0.0323835   0.8083242   0.05000726 -0.00226374]
 [-1.1121837  -0.98531127  0.17724502 -0.17199281]], shape=(2, 4), dtype=float32)


## Indexing

In [46]:
a  = tf.constant([1,2,3,4,5,6,7,8])

print(a[:])

tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)


In [49]:
print(a[::-1])

tf.Tensor([8 7 6 5 4 3 2 1], shape=(8,), dtype=int32)


In [50]:
print(x[::2])

tf.Tensor([1 3], shape=(2,), dtype=int32)


In [53]:
print(a[1:7])

tf.Tensor([2 3 4 5 6 7], shape=(6,), dtype=int32)


In [54]:
a  = tf.constant([[1,2],
                  [3,4],
                  [5,6]])

print(a[0,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [55]:
print(a[0:2,:])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [56]:
print(a[:,0])

tf.Tensor([1 3 5], shape=(3,), dtype=int32)


In [57]:
print(a[:,1])

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [59]:
print(y)

tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [64]:
m = tf.reshape(y,(1,3))
n = tf.reshape(x, (3,1))

print(m)
print(n)

tf.Tensor([[4 5 6]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [65]:
print(n @ m)

tf.Tensor(
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]], shape=(3, 3), dtype=int32)


In [71]:
s = tf.transpose(z)
print(s)

tf.Tensor(
[[-0.0323835  -1.1121837 ]
 [ 0.8083242  -0.98531127]
 [ 0.05000726  0.17724502]
 [-0.00226374 -0.17199281]], shape=(4, 2), dtype=float32)
