### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([56, 79, 27, 27, 60,  1, 38, 70, 91, 90, 68, 16,  1, 20, 68])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 9, 85, 92, 65],
       [65, 55, 78, 22],
       [10,  5, 80, 79],
       [44, 71, 24,  5],
       [57, 99, 53, 94],
       [69, 58, 40, 83]])

In [3]:
np.sort(a)[::-1]

array([91, 90, 79, 70, 68, 68, 60, 56, 38, 27, 27, 20, 16,  1,  1])

In [4]:
np.sort(b,axis=0)

array([[ 9,  5, 24,  5],
       [10, 55, 40, 22],
       [44, 58, 53, 65],
       [57, 71, 78, 79],
       [65, 85, 80, 83],
       [69, 99, 92, 94]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [5]:
# code
np.append(a,200)

array([ 56,  79,  27,  27,  60,   1,  38,  70,  91,  90,  68,  16,   1,
        20,  68, 200])

In [6]:
b

array([[ 9, 85, 92, 65],
       [65, 55, 78, 22],
       [10,  5, 80, 79],
       [44, 71, 24,  5],
       [57, 99, 53, 94],
       [69, 58, 40, 83]])

In [7]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[9.00000000e+00, 8.50000000e+01, 9.20000000e+01, 6.50000000e+01,
        9.78414067e-01],
       [6.50000000e+01, 5.50000000e+01, 7.80000000e+01, 2.20000000e+01,
        9.14604083e-01],
       [1.00000000e+01, 5.00000000e+00, 8.00000000e+01, 7.90000000e+01,
        3.23250527e-01],
       [4.40000000e+01, 7.10000000e+01, 2.40000000e+01, 5.00000000e+00,
        4.32698532e-01],
       [5.70000000e+01, 9.90000000e+01, 5.30000000e+01, 9.40000000e+01,
        8.11483352e-01],
       [6.90000000e+01, 5.80000000e+01, 4.00000000e+01, 8.30000000e+01,
        7.64451196e-02]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [8]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [11]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [12]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [13]:
# code
a.shape

(15,)

In [14]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [15]:
np.expand_dims(a,axis=1)

array([[56],
       [79],
       [27],
       [27],
       [60],
       [ 1],
       [38],
       [70],
       [91],
       [90],
       [68],
       [16],
       [ 1],
       [20],
       [68]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [16]:
a

array([56, 79, 27, 27, 60,  1, 38, 70, 91, 90, 68, 16,  1, 20, 68])

In [17]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  4,  7,  8,  9, 10, 14]),)

In [18]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0, 27, 27,  0,  1, 38,  0,  0,  0,  0, 16,  1, 20,  0])

In [19]:
np.where(a%2 == 0,0,a)

array([ 0, 79, 27, 27,  0,  1,  0,  0, 91,  0,  0,  0,  1,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [20]:
# code
a

array([56, 79, 27, 27, 60,  1, 38, 70, 91, 90, 68, 16,  1, 20, 68])

In [21]:
np.argmax(a)

8

In [22]:
b

array([[ 9, 85, 92, 65],
       [65, 55, 78, 22],
       [10,  5, 80, 79],
       [44, 71, 24,  5],
       [57, 99, 53, 94],
       [69, 58, 40, 83]])

In [23]:
np.argmax(b,axis=0)

array([5, 4, 0, 4])

In [24]:
np.argmax(b,axis=1)

array([2, 2, 2, 1, 1, 3])

In [25]:
# np.argmin
np.argmin(a)

5

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [26]:
a

array([56, 79, 27, 27, 60,  1, 38, 70, 91, 90, 68, 16,  1, 20, 68])

In [27]:
np.cumsum(a)

array([ 56, 135, 162, 189, 249, 250, 288, 358, 449, 539, 607, 623, 624,
       644, 712])

In [28]:
b

array([[ 9, 85, 92, 65],
       [65, 55, 78, 22],
       [10,  5, 80, 79],
       [44, 71, 24,  5],
       [57, 99, 53, 94],
       [69, 58, 40, 83]])

In [29]:
np.cumsum(b,axis=1)

array([[  9,  94, 186, 251],
       [ 65, 120, 198, 220],
       [ 10,  15,  95, 174],
       [ 44, 115, 139, 144],
       [ 57, 156, 209, 303],
       [ 69, 127, 167, 250]])

In [30]:
np.cumsum(b)

array([   9,   94,  186,  251,  316,  371,  449,  471,  481,  486,  566,
        645,  689,  760,  784,  789,  846,  945,  998, 1092, 1161, 1219,
       1259, 1342])

In [31]:
# np.cumprod
np.cumprod(a)

array([                 56,                4424,              119448,
                   3225096,           193505760,           193505760,
                7353218880,        514725321600,      46840004265600,
          4215600383904000,  286660826105472000, 4586573217687552000,
       4586573217687552000, -502256014796718080, 2740079141242273792])

In [32]:
a

array([56, 79, 27, 27, 60,  1, 38, 70, 91, 90, 68, 16,  1, 20, 68])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [33]:
a

array([56, 79, 27, 27, 60,  1, 38, 70, 91, 90, 68, 16,  1, 20, 68])

In [34]:
np.percentile(a,50)

56.0

In [35]:
np.median(a)

56.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [36]:
# code
a

array([56, 79, 27, 27, 60,  1, 38, 70, 91, 90, 68, 16,  1, 20, 68])

In [37]:
np.histogram(a,bins=[0,50,100])

(array([7, 8]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [38]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [39]:
# code
a


array([56, 79, 27, 27, 60,  1, 38, 70, 91, 90, 68, 16,  1, 20, 68])

In [40]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([60, 70, 90, 20])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [41]:
# code
a

array([56, 79, 27, 27, 60,  1, 38, 70, 91, 90, 68, 16,  1, 20, 68])

In [42]:
np.flip(a)

array([68, 20,  1, 16, 68, 90, 91, 70, 38,  1, 60, 27, 27, 79, 56])

In [43]:
b

array([[ 9, 85, 92, 65],
       [65, 55, 78, 22],
       [10,  5, 80, 79],
       [44, 71, 24,  5],
       [57, 99, 53, 94],
       [69, 58, 40, 83]])

In [44]:
np.flip(b,axis=1)

array([[65, 92, 85,  9],
       [22, 78, 55, 65],
       [79, 80,  5, 10],
       [ 5, 24, 71, 44],
       [94, 53, 99, 57],
       [83, 40, 58, 69]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [45]:
# code
a

array([56, 79, 27, 27, 60,  1, 38, 70, 91, 90, 68, 16,  1, 20, 68])

In [46]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [47]:
# code
a

array([110, 530,  27,  27,  60,   1,  38,  70,  91,  90,  68,  16,   1,
        20,  68])

In [48]:
np.delete(a,[0,2,4])

array([530,  27,   1,  38,  70,  91,  90,  68,  16,   1,  20,  68])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [49]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
np.intersect1d(m,n)

array([3, 4, 5])

In [51]:
np.setdiff1d(n,m)

array([6, 7])

In [52]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [53]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [54]:
# code
a

array([110, 530,  27,  27,  60,   1,  38,  70,  91,  90,  68,  16,   1,
        20,  68])

In [55]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 27, 27, 60, 25, 38, 70, 75, 75, 68, 25, 25, 25, 68])